---
title: "高雄市長候選人6月到9月表情貼比較"
author: "Kyle"
date: "2019年3月11日"
output: html_document
---

```{r}
#讀取資料
library(readr)
data6 <- read_csv("201806_data.csv")
data7 <- read_csv("201807_data.csv")
data8 <- read_csv("201808_data.csv")
data9 <- read_csv("201809_data.csv")
data10 <- read_csv("201810_data.csv")
data=rbind(data6, data7, data8,data9)
```


```{r}
#將韓國瑜與陳其邁的貼文單獨分離
library(dplyr)
Han=filter(data, grepl("韓國瑜", data$Page_Name)== T& grepl("韓國瑜粉絲團", data$Page_Name)== F& grepl("韓國瑜新聞網", data$Page_Name)== F& grepl("高雄選韓國瑜News", data$Page_Name)== F& grepl("韓國瑜民間粉絲團志工團
", data$Page_Name)== F)
planes <- group_by(Han, Page_Name)

Chen = filter(data,grepl("陳其邁",data$Page_Name) == T)
```

```{r}
#設定時間
Han$Date = as.POSIXct(Han$Date,format = "%Y/%m/%d %H:%M:%S")
Chen$Date = as.POSIXct(Chen$Date,format = "%Y/%m/%d %H:%M:%S")
```
```{r}
#兩候選人like count趨勢圖
plot(Han$Date, Han$LIKE_COUNT,xlab ="Date",ylab = "Like_count"  ,type = "l",col = "blue")
lines(Chen$Date, Chen$LIKE_COUNT,col = "green")
```
```{r}
#兩候選人angry趨勢圖
plot(Han$Date, Han$ANGRY_COUNT,xlab = "Date",ylab= "Angry_count",type = "l",col = "blue")
lines(Chen$Date, Chen$ANGRY_COUNT,type="l", col = "green")
```

```{r}
#兩候選人love_count趨勢圖
plot(Han$Date, Han$LOVE_COUNT,xlab = "Date",ylab= "LOVE_count",type = "l",col = "blue")
lines(Chen$Date, Chen$LOVE_COUNT,type="l", col = "green")

```


```{r}
plot(Han$Date, Han$WOW_COUNT,xlab = "Date",ylab= "WOW_count",type = "l",col = "blue")
lines(Chen$Date, Chen$WOW_COUNT,type="l", col = "green")
```

```{r}
plot(Han$Date, Han$SAD_COUNT,xlab = "Date",ylab= "SAD_count",type = "l",col = "blue")
lines(Chen$Date, Chen$SAD_COUNT,type="l", col = "green")
```

```{r}
plot(Han$Date, Han$HAHA_COUNT,xlab = "Date",ylab= "HAHA_count",type = "l",col = "blue")
lines(Chen$Date, Chen$HAHA_COUNT,type="l", col = "green")
```





































































































































































































































































































